# -*- coding: utf-8 -*-
"""untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Joodalhu/eda9782d5077f72053f3b7ecbbe64809/untitled4.ipynb
"""

!pip install -q langchain langgraph langchain-openai tavily-python python-dotenv

import os
from typing import TypedDict
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
from langgraph.graph import StateGraph, END


os.environ["OPENAI_API_KEY"] = "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"


llm = ChatOpenAI(
    model="openrouter/auto",
    base_url="https://openrouter.ai/api/v1",
    temperature=0.5
)


class ReportState(TypedDict):
    topic: str
    research_notes: str
    summary_notes: str
    draft_report: str
    final_report: str


def research_agent(state: ReportState):
    print("\n🔍 [1/4] Research Agent: Gathering information...")
    prompt = f"You are an expert researcher. Gather detailed notes and insights on: {state['topic']}"
    res = llm.invoke([HumanMessage(content=prompt)])
    return {"research_notes": res.content}

def summary_agent(state: ReportState):
    print("📝 [2/4] Summary Agent: Summarizing key findings...")
    prompt = f"You are a professional summarizer. Condense the following research notes into concise bullet points:\n{state['research_notes']}"
    res = llm.invoke([HumanMessage(content=prompt)])
    return {"summary_notes": res.content}

def writing_agent(state: ReportState):
    print("✍️ [3/4] Writing Agent: Drafting the full report...")
    prompt = f"You are a technical report writer. Write a comprehensive report based on these notes:\n{state['summary_notes']}"
    res = llm.invoke([HumanMessage(content=prompt)])
    return {"draft_report": res.content}

def review_agent(state: ReportState):
    print("🧐 [4/4] Review Agent: Polishing and proofreading...")
    prompt = f"You are a quality assurance editor. Polish and refine this draft report for final approval:\n{state['draft_report']}"
    res = llm.invoke([HumanMessage(content=prompt)])
    return {"final_report": res.content}

workflow = StateGraph(ReportState)

workflow.add_node("ResearchAgent", research_agent)
workflow.add_node("SummaryAgent", summary_agent)
workflow.add_node("WritingAgent", writing_agent)
workflow.add_node("ReviewAgent", review_agent)

workflow.set_entry_point("ResearchAgent")
workflow.add_edge("ResearchAgent", "SummaryAgent")
workflow.add_edge("SummaryAgent", "WritingAgent")
workflow.add_edge("WritingAgent", "ReviewAgent")
workflow.add_edge("ReviewAgent", END)

app = workflow.compile()


topic_input = "The Importance of Cybersecurity in AI Applications"
print(f"🚀 Starting Multi-Agent Workflow for Topic: '{topic_input}'")

initial_input = {"topic": topic_input}
result = app.invoke(initial_input)

print("\n==================================================")
print("✨ FINAL APPROVED REPORT ✨")
print("==================================================\n")
print(result["final_report"])



